#ifndef _HAVE_KSP_DISPLAY_DEFINES_
#define _HAVE_KSP_DISPLAY_DEFINES_

#define KSP_INPUT_YAW 1
#define KSP_INPUT_ROLL 2
#define KSP_INPUT_PITCH 3
#define KSP_INPUT_XTRANS 4
#define KSP_INPUT_YTRANS 5
#define KSP_INPUT_ZTRANS 6
#define KSP_INPUT_THRUST 7
#define BUTTON_STAGE 8
#define BUTTON_RCS 9
#define BUTTON_SAS 10
#define BUTTON_GEAR 11
#define BUTTON_SWITCH_RIGHT 12
#define BUTTON_SWITCH_LEFT 13
#define BUTTON_LIGHTS 14
#define BUTTON_BREAKS 15
#define BUTTON_ACTION_1 16
#define BUTTON_ACTION_2 17
#define BUTTON_ACTION_3 18
#define BUTTON_ACTION_4 19
#define BUTTON_ACTION_5 20
#define BUTTON_ACTION_6 21
#define BUTTON_ACTION_7 22
#define BUTTON_ACTION_8 23
#define BUTTON_ACTION_9 24
#define BUTTON_ACTION_10 25
#define BUTTON_SOLAR_ON 26
#define BUTTON_SOLAR_OFF 27

#define INFO_HEIGHT 100
#define INFO_SPEED 101
#define INFO_ACTION_GROUPS 102

#endif // _HAVE_KSP_DISPLAY_DEFINES_
